version: '3.8'
services:
  backend:
    build: . 
    command: python manage.py runserver 0.0.0.0:8000  
    ports:
      - "8000:8000"
    container_name: djbackend

  myredis:
    image: redis:7.0.14-alpine3.19
    container_name: MyRedisServer