version: '3.8'
services:
  backend:
    build: . 
    command: python manage.py runserver 0.0.0.0:8000  
    ports:
      - "8000:8000"
    container_name: djbackend
    depends_on:
      - myredis
    #   - db
    # environment:
    #   POSTGRES_DB: myDataBase
    #   POSTGRES_USER: postgre
    #   POSTGRES_PASSWORD: postgre

  myredis:
    image: redis:7.0.14-alpine3.19
    container_name: MyRedisServer

  celery:
    build: .
    command: celery -A project worker -l info
    volumes:
      - ./project:/code
    depends_on:
      - myredis
      - backend

  # db:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_DB: myDataBase
  #     POSTGRES_USER: postgre
  #     POSTGRES_PASSWORD: postgre
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:
    